# Julia wrapper for header: /opt/intel/mkl/include/mkl_vsl_defines.h
# Automatically generated using Clang.jl wrap_c, version 0.0.0

const VSL_ERROR_OK = 0
const VSL_ERROR_FEATURE_NOT_IMPLEMENTED = -1
const VSL_ERROR_UNKNOWN = -2
const VSL_ERROR_BADARGS = -3
const VSL_ERROR_MEM_FAILURE = -4
const VSL_ERROR_NULL_PTR = -5
const VSL_ERROR_CPU_NOT_SUPPORTED = -6
const VSL_RNG_ERROR_INVALID_BRNG_INDEX = -1000
const VSL_RNG_ERROR_LEAPFROG_UNSUPPORTED = -1002
const VSL_RNG_ERROR_SKIPAHEAD_UNSUPPORTED = -1003
const VSL_RNG_ERROR_BRNGS_INCOMPATIBLE = -1005
const VSL_RNG_ERROR_BAD_STREAM = -1006
const VSL_RNG_ERROR_BRNG_TABLE_FULL = -1007
const VSL_RNG_ERROR_BAD_STREAM_STATE_SIZE = -1008
const VSL_RNG_ERROR_BAD_WORD_SIZE = -1009
const VSL_RNG_ERROR_BAD_NSEEDS = -1010
const VSL_RNG_ERROR_BAD_NBITS = -1011
const VSL_RNG_ERROR_QRNG_PERIOD_ELAPSED = -1012
const VSL_RNG_ERROR_LEAPFROG_NSTREAMS_TOO_BIG = -1013
const VSL_RNG_ERROR_BRNG_NOT_SUPPORTED = -1014
const VSL_RNG_ERROR_BAD_UPDATE = -1120
const VSL_RNG_ERROR_NO_NUMBERS = -1121
const VSL_RNG_ERROR_INVALID_ABSTRACT_STREAM = -1122
const VSL_RNG_ERROR_NONDETERM_NOT_SUPPORTED = -1130
const VSL_RNG_ERROR_NONDETERM_NRETRIES_EXCEEDED = -1131
const VSL_RNG_ERROR_ARS5_NOT_SUPPORTED = -1140
const VSL_RNG_ERROR_FILE_CLOSE = -1100
const VSL_RNG_ERROR_FILE_OPEN = -1101
const VSL_RNG_ERROR_FILE_WRITE = -1102
const VSL_RNG_ERROR_FILE_READ = -1103
const VSL_RNG_ERROR_BAD_FILE_FORMAT = -1110
const VSL_RNG_ERROR_UNSUPPORTED_FILE_VER = -1111
const VSL_RNG_ERROR_BAD_MEM_FORMAT = -1200

# Skipping MacroDefinition: VSL_CC_ERROR_NOT_IMPLEMENTED ( - 2000 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_ALLOCATION_FAILURE ( - 2001 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_BAD_DESCRIPTOR ( - 2200 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_SERVICE_FAILURE ( - 2210 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_EDIT_FAILURE ( - 2211 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_EDIT_PROHIBITED ( - 2212 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_COMMIT_FAILURE ( - 2220 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_COPY_FAILURE ( - 2230 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_DELETE_FAILURE ( - 2240 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_BAD_ARGUMENT ( - 2300 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_DIMS ( - 2301 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_START ( - 2302 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_DECIMATION ( - 2303 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_XSHAPE ( - 2311 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_YSHAPE ( - 2312 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_ZSHAPE ( - 2313 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_XSTRIDE ( - 2321 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_YSTRIDE ( - 2322 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_ZSTRIDE ( - 2323 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_X ( - 2331 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_Y ( - 2332 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_Z ( - 2333 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_JOB ( - 2100 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_KIND ( - 2110 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_MODE ( - 2120 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_TYPE ( - 2130 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_PRECISION ( - 2400 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_EXTERNAL_PRECISION ( - 2141 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_INTERNAL_PRECISION ( - 2142 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_METHOD ( - 2400 ) #
# Skipping MacroDefinition: VSL_CC_ERROR_OTHER ( - 2800 ) /*
#//++
#// SUMMARY STATTISTICS ERROR/WARNING CODES
#//--
#*/

const VSL_SS_NOT_FULL_RANK_MATRIX = 4028
const VSL_SS_SEMIDEFINITE_COR = 4029
const VSL_SS_ERROR_ALLOCATION_FAILURE = -4000
const VSL_SS_ERROR_BAD_DIMEN = -4001
const VSL_SS_ERROR_BAD_OBSERV_N = -4002
const VSL_SS_ERROR_STORAGE_NOT_SUPPORTED = -4003
const VSL_SS_ERROR_BAD_INDC_ADDR = -4004
const VSL_SS_ERROR_BAD_WEIGHTS = -4005
const VSL_SS_ERROR_BAD_MEAN_ADDR = -4006
const VSL_SS_ERROR_BAD_2R_MOM_ADDR = -4007
const VSL_SS_ERROR_BAD_3R_MOM_ADDR = -4008
const VSL_SS_ERROR_BAD_4R_MOM_ADDR = -4009
const VSL_SS_ERROR_BAD_2C_MOM_ADDR = -4010
const VSL_SS_ERROR_BAD_3C_MOM_ADDR = -4011
const VSL_SS_ERROR_BAD_4C_MOM_ADDR = -4012
const VSL_SS_ERROR_BAD_KURTOSIS_ADDR = -4013
const VSL_SS_ERROR_BAD_SKEWNESS_ADDR = -4014
const VSL_SS_ERROR_BAD_MIN_ADDR = -4015
const VSL_SS_ERROR_BAD_MAX_ADDR = -4016
const VSL_SS_ERROR_BAD_VARIATION_ADDR = -4017
const VSL_SS_ERROR_BAD_COV_ADDR = -4018
const VSL_SS_ERROR_BAD_COR_ADDR = -4019
const VSL_SS_ERROR_BAD_ACCUM_WEIGHT_ADDR = -4020
const VSL_SS_ERROR_BAD_QUANT_ORDER_ADDR = -4021
const VSL_SS_ERROR_BAD_QUANT_ORDER = -4022
const VSL_SS_ERROR_BAD_QUANT_ADDR = -4023
const VSL_SS_ERROR_BAD_ORDER_STATS_ADDR = -4024
const VSL_SS_ERROR_MOMORDER_NOT_SUPPORTED = -4025
const VSL_SS_ERROR_ALL_OBSERVS_OUTLIERS = -4026
const VSL_SS_ERROR_BAD_ROBUST_COV_ADDR = -4027
const VSL_SS_ERROR_BAD_ROBUST_MEAN_ADDR = -4028
const VSL_SS_ERROR_METHOD_NOT_SUPPORTED = -4029
const VSL_SS_ERROR_BAD_GROUP_INDC_ADDR = -4030
const VSL_SS_ERROR_NULL_TASK_DESCRIPTOR = -4031
const VSL_SS_ERROR_BAD_OBSERV_ADDR = -4032
const VSL_SS_ERROR_SINGULAR_COV = -4033
const VSL_SS_ERROR_BAD_POOLED_COV_ADDR = -4034
const VSL_SS_ERROR_BAD_POOLED_MEAN_ADDR = -4035
const VSL_SS_ERROR_BAD_GROUP_COV_ADDR = -4036
const VSL_SS_ERROR_BAD_GROUP_MEAN_ADDR = -4037
const VSL_SS_ERROR_BAD_GROUP_INDC = -4038
const VSL_SS_ERROR_BAD_OUTLIERS_PARAMS_ADDR = -4039
const VSL_SS_ERROR_BAD_OUTLIERS_PARAMS_N_ADDR = -4040
const VSL_SS_ERROR_BAD_OUTLIERS_WEIGHTS_ADDR = -4041
const VSL_SS_ERROR_BAD_ROBUST_COV_PARAMS_ADDR = -4042
const VSL_SS_ERROR_BAD_ROBUST_COV_PARAMS_N_ADDR = -4043
const VSL_SS_ERROR_BAD_STORAGE_ADDR = -4044
const VSL_SS_ERROR_BAD_PARTIAL_COV_IDX_ADDR = -4045
const VSL_SS_ERROR_BAD_PARTIAL_COV_ADDR = -4046
const VSL_SS_ERROR_BAD_PARTIAL_COR_ADDR = -4047
const VSL_SS_ERROR_BAD_MI_PARAMS_ADDR = -4048
const VSL_SS_ERROR_BAD_MI_PARAMS_N_ADDR = -4049
const VSL_SS_ERROR_BAD_MI_BAD_PARAMS_N = -4050
const VSL_SS_ERROR_BAD_MI_PARAMS = -4051
const VSL_SS_ERROR_BAD_MI_INIT_ESTIMATES_N_ADDR = -4052
const VSL_SS_ERROR_BAD_MI_INIT_ESTIMATES_ADDR = -4053
const VSL_SS_ERROR_BAD_MI_SIMUL_VALS_ADDR = -4054
const VSL_SS_ERROR_BAD_MI_SIMUL_VALS_N_ADDR = -4055
const VSL_SS_ERROR_BAD_MI_ESTIMATES_N_ADDR = -4056
const VSL_SS_ERROR_BAD_MI_ESTIMATES_ADDR = -4057
const VSL_SS_ERROR_BAD_MI_SIMUL_VALS_N = -4058
const VSL_SS_ERROR_BAD_MI_ESTIMATES_N = -4059
const VSL_SS_ERROR_BAD_MI_OUTPUT_PARAMS = -4060
const VSL_SS_ERROR_BAD_MI_PRIOR_N_ADDR = -4061
const VSL_SS_ERROR_BAD_MI_PRIOR_ADDR = -4062
const VSL_SS_ERROR_BAD_MI_MISSING_VALS_N = -4063
const VSL_SS_ERROR_BAD_STREAM_QUANT_PARAMS_N_ADDR = -4064
const VSL_SS_ERROR_BAD_STREAM_QUANT_PARAMS_ADDR = -4065
const VSL_SS_ERROR_BAD_STREAM_QUANT_PARAMS_N = -4066
const VSL_SS_ERROR_BAD_STREAM_QUANT_PARAMS = -4067
const VSL_SS_ERROR_BAD_STREAM_QUANT_ORDER_ADDR = -4068
const VSL_SS_ERROR_BAD_STREAM_QUANT_ORDER = -4069
const VSL_SS_ERROR_BAD_STREAM_QUANT_ADDR = -4070
const VSL_SS_ERROR_BAD_PARAMTR_COR_ADDR = -4071
const VSL_SS_ERROR_BAD_COR = -4072
const VSL_SS_ERROR_BAD_PARTIAL_COV_IDX = -4073
const VSL_SS_ERROR_BAD_SUM_ADDR = -4074
const VSL_SS_ERROR_BAD_2R_SUM_ADDR = -4075
const VSL_SS_ERROR_BAD_3R_SUM_ADDR = -4076
const VSL_SS_ERROR_BAD_4R_SUM_ADDR = -4077
const VSL_SS_ERROR_BAD_2C_SUM_ADDR = -4078
const VSL_SS_ERROR_BAD_3C_SUM_ADDR = -4079
const VSL_SS_ERROR_BAD_4C_SUM_ADDR = -4080
const VSL_SS_ERROR_BAD_CP_ADDR = -4081
const VSL_SS_ERROR_BAD_MDAD_ADDR = -4082
const VSL_SS_ERROR_BAD_MNAD_ADDR = -4083
const VSL_SS_ERROR_ROBCOV_INTERN_C1 = -5000
const VSL_SS_ERROR_PARTIALCOV_INTERN_C1 = -5010
const VSL_SS_ERROR_PARTIALCOV_INTERN_C2 = -5011
const VSL_SS_ERROR_MISSINGVALS_INTERN_C1 = -5021
const VSL_SS_ERROR_MISSINGVALS_INTERN_C2 = -5022
const VSL_SS_ERROR_MISSINGVALS_INTERN_C3 = -5023
const VSL_SS_ERROR_MISSINGVALS_INTERN_C4 = -5024
const VSL_SS_ERROR_MISSINGVALS_INTERN_C5 = -5025
const VSL_SS_ERROR_PARAMTRCOR_INTERN_C1 = -5030
const VSL_SS_ERROR_COVRANK_INTERNAL_ERROR_C1 = -5040
const VSL_SS_ERROR_INVCOV_INTERNAL_ERROR_C1 = -5041
const VSL_SS_ERROR_INVCOV_INTERNAL_ERROR_C2 = -5042
const VSL_CONV_MODE_AUTO = 0
const VSL_CORR_MODE_AUTO = 0
const VSL_CONV_MODE_DIRECT = 1
const VSL_CORR_MODE_DIRECT = 1
const VSL_CONV_MODE_FFT = 2
const VSL_CORR_MODE_FFT = 2
const VSL_CONV_PRECISION_SINGLE = 1
const VSL_CORR_PRECISION_SINGLE = 1
const VSL_CONV_PRECISION_DOUBLE = 2
const VSL_CORR_PRECISION_DOUBLE = 2
const VSL_MAX_REG_BRNGS = 512
const VSL_BRNG_SHIFT = 20

const VSL_BRNG_INC  = ( 1 << VSL_BRNG_SHIFT )
const VSL_BRNG_MCG31  = ( VSL_BRNG_INC )
const VSL_BRNG_R250  = ( VSL_BRNG_MCG31 + VSL_BRNG_INC )
const VSL_BRNG_MRG32K3A  = ( VSL_BRNG_R250 + VSL_BRNG_INC )
const VSL_BRNG_MCG59  = ( VSL_BRNG_MRG32K3A + VSL_BRNG_INC )
const VSL_BRNG_WH  = ( VSL_BRNG_MCG59 + VSL_BRNG_INC )
const VSL_BRNG_SOBOL  = ( VSL_BRNG_WH + VSL_BRNG_INC )
const VSL_BRNG_NIEDERR  = ( VSL_BRNG_SOBOL + VSL_BRNG_INC )
const VSL_BRNG_MT19937  = ( VSL_BRNG_NIEDERR + VSL_BRNG_INC )
const VSL_BRNG_MT2203  = ( VSL_BRNG_MT19937 + VSL_BRNG_INC )
const VSL_BRNG_IABSTRACT  = ( VSL_BRNG_MT2203 + VSL_BRNG_INC )
const VSL_BRNG_DABSTRACT  = ( VSL_BRNG_IABSTRACT + VSL_BRNG_INC )
const VSL_BRNG_SABSTRACT  = ( VSL_BRNG_DABSTRACT + VSL_BRNG_INC )
const VSL_BRNG_SFMT19937  = ( VSL_BRNG_SABSTRACT + VSL_BRNG_INC )
const VSL_BRNG_NONDETERM  = ( VSL_BRNG_SFMT19937 + VSL_BRNG_INC )
const VSL_BRNG_ARS5  = ( VSL_BRNG_NONDETERM + VSL_BRNG_INC )
const VSL_BRNG_PHILOX4X32X10  = ( VSL_BRNG_ARS5 + VSL_BRNG_INC )
#// PREDEFINED PARAMETERS FOR NON-DETERMNINISTIC RANDOM NUMBER
#// GENERATOR
#// The library provides an abstraction to the source of non-deterministic
#// random numbers supported in HW. Current version of the library provides
#// interface to RDRAND-based only, available in latest Intel CPU.
#*/

const VSL_BRNG_RDRAND = 0x00
const VSL_BRNG_NONDETERM_NRETRIES = 10
const VSL_QRNG_LEAPFROG_COMPONENTS = Float32(0x07ffffff)
const VSL_USER_QRNG_INITIAL_VALUES = 0x01
const VSL_USER_PRIMITIVE_POLYMS = 0x01
const VSL_USER_INIT_DIRECTION_NUMBERS = 0x02
const VSL_USER_IRRED_POLYMS = 0x01
const VSL_USER_DIRECTION_NUMBERS = 0x04
const VSL_QRNG_OVERRIDE_1ST_DIM_INIT = 0x08
const VSL_INIT_METHOD_STANDARD = 0
const VSL_INIT_METHOD_LEAPFROG = 1
const VSL_INIT_METHOD_SKIPAHEAD = 2

const VSL_RNG_METHOD_ACCURACY_FLAG = 1 << 30
#//++
#//  TRANSFORMATION METHOD NAMES FOR DISTRIBUTION RANDOM NUMBER GENERATORS
#//  VSL interface allows more than one generation method in a distribution
#//  transformation subroutine. Following macro definitions are used to
#//  specify generation method for given distribution generator.
#//
#//  Method name macro is constructed as
#//
#//     VSL_RNG_METHOD_<Distribution>_<Method>
#//
#//  where
#//
#//     <Distribution> - probability distribution
#//     <Method> - method name
#//
#//  VSL_RNG_METHOD_<Distribution>_<Method> should be used with
#//  vsl<precision>Rng<Distribution> function only, where
#//
#//     <precision> - s (single) or d (double)
#//     <Distribution> - probability distribution
#//--
#*/

const VSL_RNG_METHOD_UNIFORM_STD = 0
const VSL_RNG_METHOD_UNIFORM_STD_ACCURATE = VSL_RNG_METHOD_UNIFORM_STD | VSL_RNG_METHOD_ACCURACY_FLAG
const VSL_RNG_METHOD_UNIFORMBITS_STD = 0
const VSL_RNG_METHOD_UNIFORMBITS32_STD = 0
const VSL_RNG_METHOD_UNIFORMBITS64_STD = 0
const VSL_RNG_METHOD_GAUSSIAN_BOXMULLER = 0
const VSL_RNG_METHOD_GAUSSIAN_BOXMULLER2 = 1
const VSL_RNG_METHOD_GAUSSIAN_ICDF = 2
const VSL_RNG_METHOD_GAUSSIANMV_BOXMULLER = 0
const VSL_RNG_METHOD_GAUSSIANMV_BOXMULLER2 = 1
const VSL_RNG_METHOD_GAUSSIANMV_ICDF = 2
const VSL_RNG_METHOD_EXPONENTIAL_ICDF = 0
const VSL_RNG_METHOD_EXPONENTIAL_ICDF_ACCURATE = VSL_RNG_METHOD_EXPONENTIAL_ICDF | VSL_RNG_METHOD_ACCURACY_FLAG
const VSL_RNG_METHOD_LAPLACE_ICDF = 0
const VSL_RNG_METHOD_WEIBULL_ICDF = 0
const VSL_RNG_METHOD_WEIBULL_ICDF_ACCURATE = VSL_RNG_METHOD_WEIBULL_ICDF | VSL_RNG_METHOD_ACCURACY_FLAG
const VSL_RNG_METHOD_CAUCHY_ICDF = 0
const VSL_RNG_METHOD_RAYLEIGH_ICDF = 0
const VSL_RNG_METHOD_RAYLEIGH_ICDF_ACCURATE = VSL_RNG_METHOD_RAYLEIGH_ICDF | VSL_RNG_METHOD_ACCURACY_FLAG
const VSL_RNG_METHOD_LOGNORMAL_BOXMULLER2 = 0
const VSL_RNG_METHOD_LOGNORMAL_ICDF = 1
const VSL_RNG_METHOD_LOGNORMAL_BOXMULLER2_ACCURATE = VSL_RNG_METHOD_LOGNORMAL_BOXMULLER2 | VSL_RNG_METHOD_ACCURACY_FLAG
const VSL_RNG_METHOD_LOGNORMAL_ICDF_ACCURATE = VSL_RNG_METHOD_LOGNORMAL_ICDF | VSL_RNG_METHOD_ACCURACY_FLAG
const VSL_RNG_METHOD_GUMBEL_ICDF = 0
const VSL_RNG_METHOD_GAMMA_GNORM = 0
const VSL_RNG_METHOD_GAMMA_GNORM_ACCURATE = VSL_RNG_METHOD_GAMMA_GNORM | VSL_RNG_METHOD_ACCURACY_FLAG
const VSL_RNG_METHOD_BETA_CJA = 0
const VSL_RNG_METHOD_BETA_CJA_ACCURATE = VSL_RNG_METHOD_BETA_CJA | VSL_RNG_METHOD_ACCURACY_FLAG
const VSL_RNG_METHOD_BERNOULLI_ICDF = 0
const VSL_RNG_METHOD_GEOMETRIC_ICDF = 0
const VSL_RNG_METHOD_BINOMIAL_BTPE = 0
const VSL_RNG_METHOD_HYPERGEOMETRIC_H2PE = 0
const VSL_RNG_METHOD_POISSON_PTPE = 0
const VSL_RNG_METHOD_POISSON_POISNORM = 1
const VSL_RNG_METHOD_POISSONV_POISNORM = 0
const VSL_RNG_METHOD_NEGBINOMIAL_NBAR = 0
const VSL_MATRIX_STORAGE_FULL = 0
const VSL_MATRIX_STORAGE_PACKED = 1
const VSL_MATRIX_STORAGE_DIAGONAL = 2
const VSL_SS_MATRIX_STORAGE_ROWS = 0x00010000
const VSL_SS_MATRIX_STORAGE_COLS = 0x00020000
const VSL_SS_MATRIX_STORAGE_FULL = 0x00000000
const VSL_SS_MATRIX_STORAGE_L_PACKED = 0x00000001
const VSL_SS_MATRIX_STORAGE_U_PACKED = 0x00000002
const VSL_SS_METHOD_FAST = 0x00000001
const VSL_SS_METHOD_1PASS = 0x00000002
const VSL_SS_METHOD_FAST_USER_MEAN = 0x00000100
const VSL_SS_METHOD_CP_TO_COVCOR = 0x00000200
const VSL_SS_METHOD_SUM_TO_MOM = 0x00000400
const VSL_SS_METHOD_SD = 0x00000004
const VSL_SS_METHOD_TBS = 0x00000008
const VSL_SS_METHOD_MI = 0x00000010
const VSL_SS_METHOD_BACON = 0x00000020
const VSL_SS_METHOD_SQUANTS_ZW = 0x00000040
const VSL_SS_METHOD_SQUANTS_ZW_FAST = 0x00000080
const VSL_SS_BACON_PARAMS_N = 3
const VSL_SS_METHOD_BACON_MAHALANOBIS_INIT = 0x00000001
const VSL_SS_METHOD_BACON_MEDIAN_INIT = 0x00000002
const VSL_SS_TBS_PARAMS_N = 4
const VSL_SS_MI_PARAMS_SIZE = 5
const VSL_SS_DNAN = 0xfff8000000000000
const VSL_SS_SNAN = 0xffc00000
const VSL_SS_SQUANTS_ZW_PARAMS_N = 1
const VSL_SS_ED_DIMEN = 1
const VSL_SS_ED_OBSERV_N = 2
const VSL_SS_ED_OBSERV = 3
const VSL_SS_ED_OBSERV_STORAGE = 4
const VSL_SS_ED_INDC = 5
const VSL_SS_ED_WEIGHTS = 6
const VSL_SS_ED_MEAN = 7
const VSL_SS_ED_2R_MOM = 8
const VSL_SS_ED_3R_MOM = 9
const VSL_SS_ED_4R_MOM = 10
const VSL_SS_ED_2C_MOM = 11
const VSL_SS_ED_3C_MOM = 12
const VSL_SS_ED_4C_MOM = 13
const VSL_SS_ED_SUM = 67
const VSL_SS_ED_2R_SUM = 68
const VSL_SS_ED_3R_SUM = 69
const VSL_SS_ED_4R_SUM = 70
const VSL_SS_ED_2C_SUM = 71
const VSL_SS_ED_3C_SUM = 72
const VSL_SS_ED_4C_SUM = 73
const VSL_SS_ED_KURTOSIS = 14
const VSL_SS_ED_SKEWNESS = 15
const VSL_SS_ED_MIN = 16
const VSL_SS_ED_MAX = 17
const VSL_SS_ED_VARIATION = 18
const VSL_SS_ED_COV = 19
const VSL_SS_ED_COV_STORAGE = 20
const VSL_SS_ED_COR = 21
const VSL_SS_ED_COR_STORAGE = 22
const VSL_SS_ED_CP = 74
const VSL_SS_ED_CP_STORAGE = 75
const VSL_SS_ED_ACCUM_WEIGHT = 23
const VSL_SS_ED_QUANT_ORDER_N = 24
const VSL_SS_ED_QUANT_ORDER = 25
const VSL_SS_ED_QUANT_QUANTILES = 26
const VSL_SS_ED_ORDER_STATS = 27
const VSL_SS_ED_GROUP_INDC = 28
const VSL_SS_ED_POOLED_COV_STORAGE = 29
const VSL_SS_ED_POOLED_MEAN = 30
const VSL_SS_ED_POOLED_COV = 31
const VSL_SS_ED_GROUP_COV_INDC = 32
const VSL_SS_ED_REQ_GROUP_INDC = 32
const VSL_SS_ED_GROUP_MEAN = 33
const VSL_SS_ED_GROUP_COV_STORAGE = 34
const VSL_SS_ED_GROUP_COV = 35
const VSL_SS_ED_ROBUST_COV_STORAGE = 36
const VSL_SS_ED_ROBUST_COV_PARAMS_N = 37
const VSL_SS_ED_ROBUST_COV_PARAMS = 38
const VSL_SS_ED_ROBUST_MEAN = 39
const VSL_SS_ED_ROBUST_COV = 40
const VSL_SS_ED_OUTLIERS_PARAMS_N = 41
const VSL_SS_ED_OUTLIERS_PARAMS = 42
const VSL_SS_ED_OUTLIERS_WEIGHT = 43
const VSL_SS_ED_ORDER_STATS_STORAGE = 44
const VSL_SS_ED_PARTIAL_COV_IDX = 45
const VSL_SS_ED_PARTIAL_COV = 46
const VSL_SS_ED_PARTIAL_COV_STORAGE = 47
const VSL_SS_ED_PARTIAL_COR = 48
const VSL_SS_ED_PARTIAL_COR_STORAGE = 49
const VSL_SS_ED_MI_PARAMS_N = 50
const VSL_SS_ED_MI_PARAMS = 51
const VSL_SS_ED_MI_INIT_ESTIMATES_N = 52
const VSL_SS_ED_MI_INIT_ESTIMATES = 53
const VSL_SS_ED_MI_SIMUL_VALS_N = 54
const VSL_SS_ED_MI_SIMUL_VALS = 55
const VSL_SS_ED_MI_ESTIMATES_N = 56
const VSL_SS_ED_MI_ESTIMATES = 57
const VSL_SS_ED_MI_PRIOR_N = 58
const VSL_SS_ED_MI_PRIOR = 59
const VSL_SS_ED_PARAMTR_COR = 60
const VSL_SS_ED_PARAMTR_COR_STORAGE = 61
const VSL_SS_ED_STREAM_QUANT_PARAMS_N = 62
const VSL_SS_ED_STREAM_QUANT_PARAMS = 63
const VSL_SS_ED_STREAM_QUANT_ORDER_N = 64
const VSL_SS_ED_STREAM_QUANT_ORDER = 65
const VSL_SS_ED_STREAM_QUANT_QUANTILES = 66
const VSL_SS_ED_MDAD = 76
const VSL_SS_ED_MNAD = 77
const VSL_SS_MEAN = 0x0000000000000001
const VSL_SS_2R_MOM = 0x0000000000000002
const VSL_SS_3R_MOM = 0x0000000000000004
const VSL_SS_4R_MOM = 0x0000000000000008
const VSL_SS_2C_MOM = 0x0000000000000010
const VSL_SS_3C_MOM = 0x0000000000000020
const VSL_SS_4C_MOM = 0x0000000000000040
const VSL_SS_SUM = 0x0000000002000000
const VSL_SS_2R_SUM = 0x0000000004000000
const VSL_SS_3R_SUM = 0x0000000008000000
const VSL_SS_4R_SUM = 0x0000000010000000
const VSL_SS_2C_SUM = 0x0000000020000000
const VSL_SS_3C_SUM = 0x0000000040000000
const VSL_SS_4C_SUM = 0x0000000080000000
const VSL_SS_KURTOSIS = 0x0000000000000080
const VSL_SS_SKEWNESS = 0x0000000000000100
const VSL_SS_VARIATION = 0x0000000000000200
const VSL_SS_MIN = 0x0000000000000400
const VSL_SS_MAX = 0x0000000000000800
const VSL_SS_COV = 0x0000000000001000
const VSL_SS_COR = 0x0000000000002000
const VSL_SS_CP = 0x0000000100000000
const VSL_SS_POOLED_COV = 0x0000000000004000
const VSL_SS_GROUP_COV = 0x0000000000008000
const VSL_SS_POOLED_MEAN = 0x0000000800000000
const VSL_SS_GROUP_MEAN = 0x0000001000000000
const VSL_SS_QUANTS = 0x0000000000010000
const VSL_SS_ORDER_STATS = 0x0000000000020000
const VSL_SS_ROBUST_COV = 0x0000000000040000
const VSL_SS_OUTLIERS = 0x0000000000080000
const VSL_SS_PARTIAL_COV = 0x0000000000100000
const VSL_SS_PARTIAL_COR = 0x0000000000200000
const VSL_SS_MISSING_VALS = 0x0000000000400000
const VSL_SS_PARAMTR_COR = 0x0000000000800000
const VSL_SS_STREAM_QUANTS = 0x0000000001000000
const VSL_SS_MDAD = 0x0000000200000000
const VSL_SS_MNAD = 0x0000000400000000
